### ISSUE TITLE
NXT Ultrasonic Sensor

### ISSUE THREAD

**Issue by jappenzeller** [byWulf/brickpi3-nodejs#2]
Code below throws a "sensor not configured or supported" error.  Python code works fine, so hardware and components are all good.  

const brickpi3 = require('brickpi3');
(async () => {
    try {
        let BP = new brickpi3.BrickPi3();
        brickpi3.utils.resetAllWhenFinished(BP);

        let sensor = brickpi3.utils.getSensor(BP, BP.PORT_1);

        console.log(await sensor.getValue());
    } catch (err) {
        console.log(err);
    }
})();

**Comment by byWulf** [comment]
Hi Jappenzeller,

please try setting the sensor type first (I understand that this information is not clear from the README, will improve! :D):

```
const brickpi3 = require('brickpi3');
(async () => {
    try {
        let BP = new brickpi3.BrickPi3();
        brickpi3.utils.resetAllWhenFinished(BP);

        let sensor = brickpi3.utils.getSensor(BP, BP.PORT_1);
        await sensor.setType(BP.SENSOR_TYPE.NXT_ULTRASONIC);    //<<<<<<<<<<

        console.log(await sensor.getValue());
    } catch (err) {
        console.log(err);
    }
})();
```

You can find a list of supported sensor types here: https://github.com/byWulf/brickpi3-nodejs/blob/master/index.js#L145
Also please see the doc-block for the setType method for additional parameters for special sensors: https://github.com/byWulf/brickpi3-nodejs/blob/master/objects/sensor.js#L12

Hope I could help! :)

**Comment by jappenzeller** [comment]
This is the error I get now.  And it is actually an nxt ultrasonic sensor.  

Error: get_sensor error: Invalid sensor data
    at spi_transfer_array.then (/home/pi/node_modules/brickpi3/index.js:822:35)
    at <anonymous>

**Comment by byWulf** [comment]
Okay then, time for debugging :) As I don't have an ultrasonic sensor to test with, I need you to edit the index.js (you should find it in you project under node_modules/brickpi3/index.js) and insert before line [819](https://github.com/byWulf/brickpi3-nodejs/blob/master/index.js#L819) a simple `console.log(reply);`.

When executing your code, you should get an additional output before the error. Please tell me that output :)

**Comment by jappenzeller** [comment]
[ 0, 0, 0, 165, 14, 1, 22 ]

**Comment by byWulf** [comment]
Thank you, you get the error "NOT_CONFIGURED". I tried to reproduce it with my touch sensor and if I press the sensor while starting the script, I get the same error (well, almost.. I get the error "NO_DATA").

It seems to be some kind of race condition. If I add a sleep between setting the sensor type and reading the value, I can't reproduce the error.

Please try the following code just to be sure it is really a race condition:
```
function sleep(time) {
    return new Promise((resolve) => {
       setTimeout(resolve, time);
    });
}

const brickpi3 = require('brickpi3');
(async () => {
    try {
        let BP = new brickpi3.BrickPi3();
        brickpi3.utils.resetAllWhenFinished(BP);

        let sensor = brickpi3.utils.getSensor(BP, BP.PORT_1);
        await sensor.setType(BP.SENSOR_TYPE.NXT_ULTRASONIC);

        await sleep(1000);

        console.log(await sensor.getValue());
    } catch (err) {
        console.log(err);
    }
})();
```

Thank you :) - Edit: sorry, added an await.

**Comment by jappenzeller** [comment]
I'm getting [ 0, 0, 0, 165, 14, 4, 0 ] now.  But still invalid sensor data error.

**Comment by jappenzeller** [comment]
Very strange, I tried with the python code to make sure everything was still working and got a sensor error. Unplugged the sensor and put back in and the python code worked.  Tried again with sleep statement and node and it worked.  Removed sleep and got the error with 4,0 as last two elements.  Put sleep back in and tried unplugging and plugging back in, node still won't work.

**Comment by byWulf** [comment]
For my touch sensor I can only reproduce it the following way:
* Press sensor
* Start script -> error
* Release sensor
* Press sensor
* Start script -> error

If I keep pressing the sensor between the script calls, the second execution will succeed without an error.

I currently have no clue where this behavor is coming from. I double checked the js code with the python code (it's practically just a convertion of their code).. perhaps it's the used SPI interface for communicating with the pi...

**Comment by jappenzeller** [comment]
Ok, little more info for you.  I put the read in a loop for 10 times in node after the sleep.  I run this program once, works fine.  Second time and after, invalid with 4,0 at the end.  I then run with python, loop shows invalid data.  I run loop again in python, first measurement shows invalid data, but rest are fine.  Run in python again, first measurement is invalid, rest are fine.  Go back to node, it works once again. But not after.

So two things that definitely seem to repeat.  Every time I run in python, first measurement is always invalid, no matter what.
Running in node with your added sleep, I can only run the program once, then always invalid data.

**Comment by jappenzeller** [comment]
Is it possible there's some type of "close" functionality that's missing? Like a stream is left open? (No clue how that SPI interface works.)

**Comment by byWulf** [comment]
This should be done by the `resetAllWhenFinished()` call. But I haven't  tested that hard enough to be sure it works as expected.

I see one possible bug while migrating the codebase to nodejs (procedual -> asynchronous.. yey). 

Could you please try replacing in the node_modules/brickpi3/index.js the method `this.reset_all` at the very end with the following code?

```
    this.reset_all = async () => {
        await this.set_sensor_type(this.PORT_1, this.SENSOR_TYPE.NONE);
        await this.set_sensor_type(this.PORT_2, this.SENSOR_TYPE.NONE);
        await this.set_sensor_type(this.PORT_3, this.SENSOR_TYPE.NONE);
        await this.set_sensor_type(this.PORT_4, this.SENSOR_TYPE.NONE);

        await this.set_motor_power(this.PORT_A, this.MOTOR_FLOAT);
        await this.set_motor_power(this.PORT_B, this.MOTOR_FLOAT);
        await this.set_motor_power(this.PORT_C, this.MOTOR_FLOAT);
        await this.set_motor_power(this.PORT_D, this.MOTOR_FLOAT);

        await this.set_motor_limits(this.PORT_A);
        await this.set_motor_limits(this.PORT_B);
        await this.set_motor_limits(this.PORT_C);
        await this.set_motor_limits(this.PORT_D);

        await this.set_motor_position_kp(this.PORT_A);
        await this.set_motor_position_kp(this.PORT_B);
        await this.set_motor_position_kp(this.PORT_C);
        await this.set_motor_position_kp(this.PORT_D);

        await this.set_motor_position_kd(this.PORT_A);
        await this.set_motor_position_kd(this.PORT_B);
        await this.set_motor_position_kd(this.PORT_C);
        await this.set_motor_position_kd(this.PORT_D);
        
        await this.set_led(-1);
    };
```

(yea its ugly, but its just a test :D)

**Comment by jappenzeller** [comment]
Actually my fault, i had the resetall commented out and didn't notice,  Now that it's back in there, there is no problem running multiple times.  I even took the sleep out and it seems to work.  Sorry, changing the code so many times losing track a bit.

**Comment by byWulf** [comment]
Woot! That's great news! Glad it works now :D

**Comment by jappenzeller** [comment]
Yah, I may have been missing the await on the settype initially, not sure.  But all seems good now. Thanks for the help!
